version: '3'

services:

    php72:
        build: 
            context: .
            dockerfile: php72.Dockerfile
        ports:
          - "8000:8000" #前端production端口
          - "5000:5000" #前端development端口
        volumes:
            - ./code:/home/work/code    #挂载代码目录 宿主机目录请自行修改
            - ./code/var:/home/work/var    #挂在storage目录
        container_name: php72
        privileged: true
        depends_on:
          - db
          - redis
        networks:
            - code-network

    redis:
        image: redis:4.0.10-alpine
        ports:
          - "6379:6379"
        volumes:
          - ./redis/data:/data   #挂载redis存储数据  宿主机目录请自行修改
        privileged: true
        container_name: redis
        networks:
            - code-network

    nginx:
        image: nginx:1.14-alpine
        ports:
            - "8001:8001"
            - "8002:8002"
            - "8003:8003"
            - "8004:8004"
            - "8005:8005"
            - "8006:8006"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf 
            - ./nginx/logs:/home/work/var/nginx_logs #挂载nginx 日志文件
            - ./public:/home/work/code/lps/public #挂载项目的前端静态资源
        container_name: nginx
        depends_on:
          - php72
        networks:
            - code-network

    db:
        image: mysql:5.7.22
        ports:
          - "3306:3306"
        volumes:
          - ./mysql/data:/var/lib/mysql    #挂载mysql存储数据   宿主机目录请自行修改
          - ./mysql/config:/etc/mysql
        privileged: true
        container_name: mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123   #root用户密码
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
