#gitlab-ce build by docker-compose

web:
  image: 'gitlab/gitlab-ce:11.7.0-ce.0'
  restart: always
  hostname: 'git.xxx.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://git.xxx.com:10080'
      gitlab_rails['gitlab_shell_ssh_port'] = 10022
  ports:
    - '10080:10080'
    - '10022:22'
    - '10443:443'
  volumes:
    - '/mnt/gitlab/config:/etc/gitlab'
    - '/mnt/gitlab/logs:/var/log/gitlab'
    - '/mnt/gitlab/data:/var/opt/gitlab'
