version: '2.2'
services: 
  es01:
    image: registry.cn-beijing.aliyuncs.com/ychy/elastic:es-7.9.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/resource:/usr/share/elasticsearch/resource
      - ./elastic/data1:/usr/share/elasticsearch/data
      - ./elastic/plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  es02:
    image: registry.cn-beijing.aliyuncs.com/ychy/elastic:es-7.9.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/resource:/usr/share/elasticsearch/resource
      - ./elastic/data2:/usr/share/elasticsearch/data
      - ./elastic/plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  kibana:
    image: registry.cn-beijing.aliyuncs.com/ychy/elastic:kibana-7.9.2
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    depends_on:
      - es01
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /application
    volumes:
        - ./nginx:/application
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/log:/var/log/nginx
    ports:
        - "8800:80"
    networks:
        - elastic
    depends_on:
        - kibana

networks:
  elastic:
    driver: bridge
